### ISSUE TITLE
fattal error

### ISSUE THREAD

**Issue by sam-handa** [BrightLocal/BrightLocal-API-Helper#9]
i got this error any suggestion
Fatal error: Call to a member function getStatusCode() on null in C:\xampp\htdocs\BrightLocal\src\BrightLocal\Api.php on line 89

**Comment by halfnibble** [comment]
I just started getting that too.

**Comment by halfnibble** [comment]
Except mine is on line 90.

**Comment by joey-dc** [comment]
@sam-handa @halfnibble  change your composer.json file codes back from "guzzlehttp/guzzle": "~6.0" to "guzzlehttp/guzzle": "~4.0" . Brightlocal developer didn't use the latest function of guzzle, as a result, we should use an earlier version such as 4.0
